### ISSUE TITLE
Two-factor dosnt work

### ISSUE THREAD

**Issue by Adenser** [rpgeS/Steam-Hour-Boost#1]
![image](https://user-images.githubusercontent.com/39248856/47029230-55716200-d16b-11e8-9a5f-225ea8a07f24.png)
As a title says....

**Comment by MikkelDK** [comment]
it do works. because you need to use the "shared secret" ;)

**Comment by Adenser** [comment]
ooooh, I forgot its a thing. jesus.

**Comment by MikkelDK** [comment]
no problem @Adenser you can just close the issue :D
