### ISSUE TITLE
Steam guard problem.

### ISSUE THREAD

**Issue by TechnoWolfEver** [rpgeS/Steam-Hour-Boost#3]
Hey,
I setuped the bot,
Problem is after authentication in the config after each start i get new mail for verification but i cant give the console the code cause there is no console
![hourbot](https://user-images.githubusercontent.com/46536097/50916792-54836000-143c-11e9-989a-cd9d3946e955.png)

**Comment by rpgeS** [comment]
Hey Guys, this project is outdated, use this instead: https://github.com/frk1/steamhourboostv2
