### ISSUE TITLE
cant login to my steam account

### ISSUE THREAD

**Issue by ItsLukass** [rpgeS/Steam-Hour-Boost#4]
so i just installed the script and when i use coffee user.coffee it launches the script it works fine until i put in my password
after that i get an error 

https://gyazo.com/e16545c8b1bdffa095df100f6b7b2176

i have 2 vps server and the problem is happening on both of them

**Comment by pathetic-dream** [comment]
same for me

**Comment by ItsLukass** [comment]
guess this project is dead

**Comment by rpgeS** [comment]
Hey Guys, this project is outdated, use this instead: https://github.com/frk1/steamhourboostv2
